# This is a basic workflow to help you get started with Actions

name: Production Release

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
    
  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Generate release name
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Commit latest version
      run: |
        latest_version="$(git describe --match "[0-9]*\.[0-0]*\.[0-9]*"
          --abbrev=0 --tags)"
         change_to="versionName "\"$latest_version"\""
         sed -i "0, /versionName/{/.*versionName.*/$change_to/}"
            HyperVid/build.gradle
        
         git commit -m "Bump version release for $latest_version" -
        |
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: release/beta
        github_token: ${{secrets.GITHUB_TOKEN}}
        
  unitTest:
    name: Run unit tests
    runs-on: ubuntu-latest
    needs: [build]  
    steps:
      - uses: actions/checkout@v2
      - name: Run unit tests
        run: ./gradlew
  

     
